                                          PNT2022TMID14448          711319EC135-Vishnu raj S

                                                            BASIC PYTHON

1. Split the string

In [1]:
s = "Hi there Sam!"

In [2]:
s="Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


2. Use .format() to print the following string

In [ ]:
planet='Earth'
diameter=12742

In [3]:
planet='Earth'
diameter=12742
print('The diameter of {} is {} kilometers'.format(planet,diameter))

The diameter of Earth is 12742 kilometers


3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
print(d['k1'][3]["tricky"][3]['target'][3])

hello


Numpy

In [7]:
import numpy as np

4.1 Create an array of 10 zeros?

In [9]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.2 Create an array of 10 fives?

In [10]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Create an array of the even integers from 20 to 35

In [11]:
import numpy as np 

In [13]:
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Concatenate a and b

a=np.array([1,2,3]),b=np.array([4,5,6])

In [15]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [16]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

Pandas

8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd

In [18]:
data=[2,4,6]

In [20]:
df = pd.DataFrame(data, columns=['Even Numbers'])
df

Even Numbers
0             2
1             4
2             6

9.Generate a series of dates from 1st Jan,2023 to 10th Feb,2023

In [41]:
import datetime as dt
import pandas as pd
start = dt.date(2023,1,1)
end = dt.date(2023,2,10)
dates_temp = pd.date_range(start,end)
dates = []
index_s = []
for i in dates_temp.strftime("%b %d, %Y"):
  dates.append(i)
s = pd.Series(dates)
s.index += 1
print(s)

1     Jan 01, 2023
2     Jan 02, 2023
3     Jan 03, 2023
4     Jan 04, 2023
5     Jan 05, 2023
6     Jan 06, 2023
7     Jan 07, 2023
8     Jan 08, 2023
9     Jan 09, 2023
10    Jan 10, 2023
11    Jan 11, 2023
12    Jan 12, 2023
13    Jan 13, 2023
14    Jan 14, 2023
15    Jan 15, 2023
16    Jan 16, 2023
17    Jan 17, 2023
18    Jan 18, 2023
19    Jan 19, 2023
20    Jan 20, 2023
21    Jan 21, 2023
22    Jan 22, 2023
23    Jan 23, 2023
24    Jan 24, 2023
25    Jan 25, 2023
26    Jan 26, 2023
27    Jan 27, 2023
28    Jan 28, 2023
29    Jan 29, 2023
30    Jan 30, 2023
31    Jan 31, 2023
32    Feb 01, 2023
33    Feb 02, 2023
34    Feb 03, 2023
35    Feb 04, 2023
36    Feb 05, 2023
37    Feb 06, 2023
38    Feb 07, 2023
39    Feb 08, 2023
40    Feb 09, 2023
41    Feb 10, 2023
dtype: object


10. Create 2D list to DataFrame

In [40]:
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]

In [22]:
import pandas as pd
df = pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
